import type { WorkshopType } from "../types";

export const workshopTypesById: Record<number, WorkshopType> = {
  600: {
    id: 600,
    code: "2030Glorieuses",
    logo: "logo_2030Glorieuses.webp",
    name: "Atelier 2030 Glorieuses",
    promoted: true,
    website: "https://www.2030glorieuses.org/",
    styleCode: "_atelier2030Glorieuses",
  },
  500: {
    id: 500,
    code: "FresqueFrontieresPlanetaires",
    logo: "logo_FDFP.webp",
    name: "Fresque des frontières planétaires",
    promoted: true,
    website: "https://fresquefrontieresplanetaires.earth/",
    styleCode: "_fresqueFrontieresPlanetaires",
  },
  501: {
    id: 501,
    code: "HorizonsDecarbones",
    logo: "logo_HD.webp",
    name: "Atelier Horizons Décarbonés",
    promoted: true,
    website: "https://www.horizons-decarbones.earth/",
    styleCode: "_horizonsDecarbones",
  },
  300: {
    id: 300,
    code: "FresqueEcoCirculaire",
    logo: "logo_fresqueEcoCirculaire.webp",
    name: "Fresque de l'éconameie circulaire",
    promoted: true,
    website: "https://www.lafresquedeleconameiecirculaire.com/",
    styleCode: "_fresqueEcoCirc",
  },
  200: {
    id: 200,
    code: "FresqueClimat",
    logo: "logo_fresqueClimat.png",
    name: "Fresque du Climat",
    promoted: true,
    website: "https://fresqueduclimat.org/",
    styleCode: "_fresqueClimat",
  },
  100: {
    id: 100,
    code: "2tonnes",
    logo: "logo_2tonnes.webp",
    name: "2tonnes",
    promoted: true,
    website: "https://www.2tonnes.org/",
    styleCode: "_2tonnes",
  },
  2: {
    id: 2,
    code: "FresqueBiodiversite",
    logo: "logo_fresqueBiodiversite.svg",
    name: "Fresque de la Biodiversité",
    promoted: true,
    website: "https://www.fresquedelabiodiversite.org/",
    styleCode: "_fresqueBiodiversite",
  },
  1: {
    id: 1,
    code: "FresqueOceane",
    logo: "logo_fresqueOceane.webp",
    name: "Fresque Océane",
    promoted: true,
    website: "https://www.fresqueoceane.org/",
    styleCode: "_fresqueOceane",
  },
  4: {
    id: 4,
    code: "FresqueAgriAlim",
    logo: "logo_fresqueAgriAlim.webp",
    name: "Fresque Agri'Alim",
    promoted: true,
    website: "https://fresqueagrialim.org/",
    styleCode: "_fresqueAgriAlim",
  },
  3: {
    id: 3,
    code: "FresqueNumerique",
    logo: "logo_fresqueNumerique.png",
    name: "Fresque du Numérique",
    promoted: true,
    website: "https://www.fresquedunumerique.org/",
    styleCode: "_fresqueNumerique",
  },
  0: {
    id: 0,
    code: "FresqueNouveauxRecits",
    logo: "logo_fresqueNouveauxRecits.webp",
    name: "Fresque des Nouveaux Récits",
    promoted: true,
    website: "https://www.fresquedesnouveauxrecits.org/",
    styleCode: "_fresqueNouveauRevits",
  },
  7: {
    id: 7,
    code: "FresqueMobilite",
    logo: "logo_fresqueMobilite.png",
    name: "Fresque de la Mobilité",
    promoted: true,
    website: "https://fresquedelamobilite.org/",
    styleCode: "_fresqueMobilite",
  },
  5: {
    id: 5,
    code: "FresqueAlimentation",
    logo: "logo_fresqueAlimentation.svg",
    name: "Fresque de l'Alimentation",
    promoted: true,
    website: "https://fresquealimentation.org/",
    styleCode: "_fresqueAlimentation",
  },
  9: {
    id: 9,
    code: "OGRE",
    logo: "logo_OGRE.png",
    name: "OGRE",
    promoted: true,
    website: "https://atelierogre.org/",
    styleCode: "_logoOGRE",
  },
  6: {
    id: 6,
    code: "FresqueConstruction",
    logo: "logo_fresqueConstruction.webp",
    name: "Fresque de la Construction",
    promoted: true,
    website: "https://www.fresquedelaconstruction.org/",
    styleCode: "_fresqueConstruction",
  },
  8: {
    id: 8,
    code: "FresqueSexisme",
    logo: "logo_fresqueSexisme.png",
    name: "Fresque du Sexisme",
    promoted: true,
    website: "https://fresque-du-sexisme.org/",
    styleCode: "_fresqueSexisme",
  },
  10: {
    id: 10,
    code: "AtelierNosViesBasCarbone",
    logo: "logo_NVBC.webp",
    name: "Nos Vies Bas Carbone",
    promoted: true,
    website: "https://www.nosviesbascarbone.org/",
    styleCode: "_atelierNVBC",
  },
  11: {
    id: 11,
    code: "FresqueDeLeau",
    logo: "logo_fresqueDeLeau.webp",
    name: "Fresque de l'Eau",
    promoted: true,
    website: "https://www.eaudyssee.org/",
    styleCode: "_fresqueDeLeau",
  },
  12: {
    id: 12,
    code: "FutursProches",
    logo: "logo_FutursProches.webp",
    name: "Futurs Proches",
    promoted: true,
    website: "https://futursproches.com/",
    styleCode: "_futursProches",
  },
  13: {
    id: 13,
    code: "FresqueDiversite",
    logo: "logo_fresqueDiversite.webp",
    name: "Fresque de la Diversité",
    promoted: true,
    website: "https://fresquedeladiversite.org/",
    styleCode: "_fresqueDiversite",
  },
  14: {
    id: 14,
    code: "FresqueDuTextile",
    logo: "logo_FresqueTextile.webp",
    name: "Fresque du Textile",
    promoted: true,
    website: "https://greendonut.org/",
    styleCode: "_fresqueTextile",
  },
  15: {
    id: 15,
    code: "FresqueDesDechets",
    logo: "logo_greenDonut.webp",
    name: "Fresque des Déchets",
    promoted: false,
    website: "https://greendonut.org/",
    styleCode: "_fresqueDechets",
  },
  16: {
    id: 16,
    code: "PuzzleClimat",
    logo: "logo_puzzleClimat.webp",
    name: "Puzzle Climat",
    promoted: true,
    website: "https://www.puzzleclimat.org/",
    styleCode: "_puzzleClimat",
  },
  17: {
    id: 17,
    code: "FresqueFinance",
    logo: "logo_fresqueFinance.webp",
    name: "Fresque de la finance",
    promoted: true,
    website: "",
    styleCode: "_fresqueFinance",
  },
  18: {
    id: 18,
    code: "FresqueRSE",
    logo: "logo_FresqueRSE.webp",
    name: "Fresque de la RSE",
    promoted: true,
    website: "https://fresquedelarse.org/",
    styleCode: "_fresqueRSE",
  },
};

export const workshopTypes = Object.values(workshopTypesById);
