name: daily deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with: { ref: main }
    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.DEPLOY_HOOK_URL }}
        method: 'GET'