name: Daily deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '46 23,11 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Production'
     
    steps:
    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.DEPLOY_HOOK_URL }}
